/**
@file   zip_cmd_lst.h - Z-wave command list header file.

@author David Chow

@version    1.0 13-12-17  Initial release

@copyright © 2017 SIGMA DESIGNS, INC. THIS IS AN UNPUBLISHED WORK PROTECTED BY SIGMA DESIGNS, INC.
AS A TRADE SECRET, AND IS NOT TO BE USED OR DISCLOSED EXCEPT AS PROVIDED Z-WAVE CONTROLLER DEVELOPMENT KIT
LIMITED LICENSE AGREEMENT. ALL RIGHTS RESERVED.

NOTICE: ALL INFORMATION CONTAINED HEREIN IS CONFIDENTIAL AND/OR PROPRIETARY TO SIGMA DESIGNS
AND MAY BE COVERED BY U.S. AND FOREIGN PATENTS, PATENTS IN PROCESS, AND ARE PROTECTED BY TRADE SECRET
OR COPYRIGHT LAW. DISSEMINATION OR REPRODUCTION OF THE SOURCE CODE CONTAINED HEREIN IS EXPRESSLY FORBIDDEN
TO ANYONE EXCEPT LICENSEES OF SIGMA DESIGNS  WHO HAVE EXECUTED A SIGMA DESIGNS' Z-WAVE CONTROLLER DEVELOPMENT KIT
LIMITED LICENSE AGREEMENT. THE COPYRIGHT NOTICE ABOVE IS NOT EVIDENCE OF ANY ACTUAL OR INTENDED PUBLICATION OF
THE SOURCE CODE. THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR
IMPLY ANY RIGHTS  TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL A PRODUCT
THAT IT  MAY DESCRIBE.


THE SIGMA PROGRAM AND ANY RELATED DOCUMENTATION OR TOOLS IS PROVIDED TO COMPANY "AS IS" AND "WITH ALL FAULTS",
WITHOUT WARRANTY OF ANY KIND FROM SIGMA. COMPANY ASSUMES ALL RISKS THAT LICENSED MATERIALS ARE SUITABLE OR ACCURATE
FOR COMPANY'S NEEDS AND COMPANY'S USE OF THE SIGMA PROGRAM IS AT COMPANY'S OWN DISCRETION AND RISK. SIGMA DOES NOT
GUARANTEE THAT THE USE OF THE SIGMA PROGRAM IN A THIRD PARTY SERVICE ENVIRONMENT OR CLOUD SERVICES ENVIRONMENT WILL BE:
(A) PERFORMED ERROR-FREE OR UNINTERRUPTED; (B) THAT SIGMA WILL CORRECT ANY THIRD PARTY SERVICE ENVIRONMENT OR
CLOUD SERVICE ENVIRONMENT ERRORS; (C) THE THIRD PARTY SERVICE ENVIRONMENT OR CLOUD SERVICE ENVIRONMENT WILL
OPERATE IN COMBINATION WITH COMPANY'S CONTENT OR COMPANY APPLICATIONS THAT UTILIZE THE SIGMA PROGRAM;
(D) OR WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEMS, SERVICES OR DATA NOT PROVIDED BY SIGMA. COMPANY ACKNOWLEDGES
THAT SIGMA DOES NOT CONTROL THE TRANSFER OF DATA OVER COMMUNICATIONS FACILITIES, INCLUDING THE INTERNET, AND THAT
THE SERVICES MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF SUCH COMMUNICATIONS
FACILITIES. SIGMA IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH ISSUES.
SIGMA IS NOT RESPONSIBLE FOR ANY ISSUES RELATED TO THE PERFORMANCE, OPERATION OR SECURITY OF THE THIRD PARTY SERVICE
ENVIRONMENT OR CLOUD SERVICES ENVIRONMENT THAT ARISE FROM COMPANY CONTENT, COMPANY APPLICATIONS OR THIRD PARTY CONTENT.
SIGMA DOES NOT MAKE ANY REPRESENTATION OR WARRANTY REGARDING THE RELIABILITY, ACCURACY, COMPLETENESS, CORRECTNESS, OR
USEFULNESS OF THIRD PARTY CONTENT OR SERVICE OR THE SIGMA PROGRAM, AND DISCLAIMS ALL LIABILITIES ARISING FROM OR RELATED
TO THE SIGMA PROGRAM OR THIRD PARTY CONTENT OR SERVICES. TO THE EXTENT NOT PROHIBITED BY LAW, THESE WARRANTIES ARE EXCLUSIVE.
SIGMA OFFERS NO WARRANTY OF NON-INFRINGEMENT, TITLE, OR QUIET ENJOYMENT. NEITHER SIGMA NOR ITS SUPPLIERS OR LICENSORS
SHALL BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES OR LOSS (INCLUDING DAMAGES FOR LOSS OF
BUSINESS, LOSS OF PROFITS, OR THE LIKE), ARISING OUT OF THIS AGREEMENT WHETHER BASED ON BREACH OF CONTRACT,
INTELLECTUAL PROPERTY INFRINGEMENT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, PRODUCT LIABILITY OR OTHERWISE,
EVEN IF SIGMA OR ITS REPRESENTATIVES HAVE BEEN ADVISED OF OR OTHERWISE SHOULD KNOW ABOUT THE POSSIBILITY OF SUCH DAMAGES.
THERE ARE NO OTHER EXPRESS OR IMPLIED WARRANTIES OR CONDITIONS INCLUDING FOR SOFTWARE, HARDWARE, SYSTEMS, NETWORKS OR
ENVIRONMENTS OR FOR MERCHANTABILITY, NONINFRINGEMENT, SATISFACTORY QUALITY AND FITNESS FOR A PARTICULAR PURPOSE.

The Sigma Program  is not fault-tolerant and is not designed, manufactured or intended for use or resale as on-line control
equipment in hazardous environments requiring fail-safe performance, such as in the operation of nuclear facilities,
aircraft navigation or communication systems, air traffic control, direct life support machines, or weapons systems,
in which the failure of the Sigma Program, or Company Applications created using the Sigma Program, could lead directly
to death, personal injury, or severe physical or environmental damage ("High Risk Activities").  Sigma and its suppliers
specifically disclaim any express or implied warranty of fitness for High Risk Activities.Without limiting Sigma's obligation
of confidentiality as further described in the Z-Wave Controller Development Kit Limited License Agreement, Sigma has no
obligation to establish and maintain a data privacy and information security program with regard to Company's use of any
Third Party Service Environment or Cloud Service Environment. For the avoidance of doubt, Sigma shall not be responsible
for physical, technical, security, administrative, and/or organizational safeguards that are designed to ensure the
security and confidentiality of the Company Content or Company Application in any Third Party Service Environment or
Cloud Service Environment that Company chooses to utilize.
*/

#ifndef _ZIP_CMD_LIST_DAVID_
#define _ZIP_CMD_LIST_DAVID_
/**
@defgroup Cmd_Lst Z-wave command list
Used to find the command type e.g. set, get, report
@ingroup zwarecapi
@{
*/

/** Set command list*/
static const uint16_t    zw_set_cmd_tbl[] = {
    //Note: The format must be "command class1", "set command1",
    //                         "command class1", "set command2",
    //                         "command class2", "set command1", etc.
    //Important: Make sure all the set commands belong to the same command class be grouped together sequentially.
    //
    COMMAND_CLASS_BASIC, BASIC_SET,
    COMMAND_CLASS_SWITCH_MULTILEVEL, SWITCH_MULTILEVEL_SET,
    COMMAND_CLASS_SWITCH_MULTILEVEL, SWITCH_MULTILEVEL_START_LEVEL_CHANGE,
    COMMAND_CLASS_SWITCH_MULTILEVEL, SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE,
    COMMAND_CLASS_SWITCH_BINARY, SWITCH_BINARY_SET,
    COMMAND_CLASS_DOOR_LOCK, DOOR_LOCK_OPERATION_SET,
    COMMAND_CLASS_DOOR_LOCK, DOOR_LOCK_CONFIGURATION_SET,
    COMMAND_CLASS_SWITCH_ALL, SWITCH_ALL_SET,
    COMMAND_CLASS_SWITCH_ALL, SWITCH_ALL_ON,
    COMMAND_CLASS_SWITCH_ALL, SWITCH_ALL_OFF,
    COMMAND_CLASS_POWERLEVEL, POWERLEVEL_SET,
    COMMAND_CLASS_POWERLEVEL, POWERLEVEL_TEST_NODE_SET,
    COMMAND_CLASS_ASSOCIATION, ASSOCIATION_SET,
    COMMAND_CLASS_METER, METER_RESET_V2,
    COMMAND_CLASS_SIMPLE_AV_CONTROL, SIMPLE_AV_CONTROL_SET,
    COMMAND_CLASS_CONFIGURATION, CONFIGURATION_SET,
    COMMAND_CLASS_CONFIGURATION, CONFIGURATION_BULK_SET_V2,
    COMMAND_CLASS_INDICATOR, INDICATOR_SET,
    COMMAND_CLASS_PROTECTION, PROTECTION_SET,
    COMMAND_CLASS_PROTECTION, PROTECTION_EC_SET_V2,
    COMMAND_CLASS_SWITCH_TOGGLE_BINARY, SWITCH_TOGGLE_BINARY_SET,
    COMMAND_CLASS_THERMOSTAT_FAN_MODE, THERMOSTAT_FAN_MODE_SET,
    COMMAND_CLASS_THERMOSTAT_MODE, THERMOSTAT_MODE_SET,
    COMMAND_CLASS_THERMOSTAT_SETPOINT, THERMOSTAT_SETPOINT_SET,
    COMMAND_CLASS_THERMOSTAT_SETBACK, THERMOSTAT_SETBACK_SET,
    COMMAND_CLASS_CLOCK, CLOCK_SET,
    COMMAND_CLASS_LOCK, LOCK_SET,
    COMMAND_CLASS_CLIMATE_CONTROL_SCHEDULE, SCHEDULE_OVERRIDE_SET,
    COMMAND_CLASS_SCENE_ACTIVATION, SCENE_ACTIVATION_SET,
    COMMAND_CLASS_SCENE_ACTUATOR_CONF, SCENE_ACTUATOR_CONF_SET,
    COMMAND_CLASS_SCENE_CONTROLLER_CONF, SCENE_CONTROLLER_CONF_SET,
    COMMAND_CLASS_BARRIER_OPERATOR, BARRIER_OPERATOR_SET,
    COMMAND_CLASS_SWITCH_COLOR, SWITCH_COLOR_SET
};


/**
@}
*/


#endif /* _ZIP_DEV_DEV_POLL_DAVID_ */


